### PR TITLE
Test Cases

### PR DESCRIPTION
**Pull request by pranavjain**
I have added test case under GSOC 2016 task.
It will check that DialCandidate has only value in array and will then match the relevant field.

### CODE REVIEW

**Comment by dpocock** [comment]
@pranavjain the unit tests are failing in travis-ci, can you please look at the log (use the "Details" link on this page) and try to fix the problem?

**Comment by dpocock** [comment]
do the unit tests work when you run them from the command line with `mvn`?  If you fix that, it will also fix it for travis-ci

**Comment by pranavjain** [comment]
I have fixed the issues and it is building now.
Issue: By default travis was looking for test cases in test directory only. Fixed it by changing pom.xml

**Comment by pranavjain** [comment]
I have updated the directory of test cases and reverted the pom files.

**Comment by dpocock** [comment]
@saghul @pranavjain thanks, the tests run now so I'll merge it

**Pull request merged**
